# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a16b652bcd8320526ed725d3ce8d5b1a81c5bd44522659c5dac0ea5fdc6158fdcc5343f36e78801061940fd7dc4281bc5cb12cde814803df153627f9eb9637e

test:
  secret_key_base: 1d0fe87d3f14248e80a73bb5ce0ff1cdd2d34edf5225623f3e98be287d04ffe97d6913eaa70de31b2c9080887aa243f779240d71cce0f2fb2bd7828660a0aa83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
